import unittest

from typing import List

def gcd(a: int, b: int) -> int:
    if a < b:
        return gcd(b, a)
    if a % b == 0:
        return b
    return gcd(b, a % b)


def power(x: int, y: int, mod: int) -> int:
    if y == 0:
        return 1
    temp = power(x, y // 2, mod) % mod
    temp = (temp * temp) % mod
    if y % 2 == 1:
        temp = (temp * x) % mod
    return temp


def is_carmichael_number(n: int) -> bool:
    b = 2
    while b < n:
        if gcd(b, n) == 1 and power(b, n - 1, n) != 1:
            return False
        b += 1
    return True


class TestCarmichaelNumber(unittest.TestCase):
    def test_is_carmichael_number(self):
        self.assertTrue(is_carmichael_number(561))
        self.assertTrue(is_carmichael_number(1105))
        self.assertFalse(is_carmichael_number(7))
        self.assertFalse(is_carmichael_number(13))
        self.assertFalse(is_carmichael_number(17))
        self.assertFalse(is_carmichael_number(19))
        self.assertFalse(is_carmichael_number(23))
        self.assertFalse(is_carmichael_number(29))
        self.assertFalse(is_carmichael_number(31))
        self.assertFalse(is_carmichael_number(37))
        self.assertFalse(is_carmichael_number(41))
        self.assertFalse(is_carmichael_number(43))
        self.assertFalse(is_carmichael_number(47))
        self.assertFalse(is_carmichael_number(53))
        self.assertFalse(is_carmichael_number(59))
        self.assertFalse(is_carmichael_number(61))
        self.assertFalse(is_carmichael_number(67))
        self.assertFalse(is_carmichael_number(71))
        self.assertFalse(is_carmichael_number(73))
        self.assertFalse(is_carmichael_number(79))
        self.assertFalse(is_carmichael_number(83))
        self.assertFalse(is_carmichael_number(89))
        self.assertFalse(is_carmichael_number(97))
        self.assertFalse(is_carmichael_number(101))
        self.assertFalse(is_carmichael_number(103))
        self.assertFalse(is_carmichael_number(107))
        self.assertFalse(is_carmichael_number(109))
        self.assertFalse(is_carmichael_number(113))
        self.assertFalse(is_carmichael_number(127))
        self.assertFalse(is_carmichael_number(131))
        self.assertFalse(is_carmichael_number(137))
        self.assertFalse(is_carmichael_number(139))
        self.assertFalse(is_carmichael_number(149))
        self.assertFalse(is_carmichael_number(151))
        self.assertFalse(is_carmichael_number(157))
        self.assertFalse(is_carmichael_number(163))
        self.assertFalse(is_carmichael_number(167))
        self.assertFalse(is_carmichael_number(173))
        self.assertFalse(is_carmichael_number(179))
        self.assertFalse(is_carmichael_number(181))
        self.assertFalse(is_carmichael_number(191))
        self.assertFalse(is_carmichael_number(193))
        self.assertFalse(is_carmichael_number(197))
        self.assertFalse(is_carmichael_number(199))
        self.assertFalse(is_carmichael_number(211))
        self.assertFalse(is_carmichael_number(223))
        self.assertFalse(is_carmichael_number(227))
        self.assertFalse(is_carmichael_number(229))
        self.assertFalse(is_carmichael_number(233))
        self.assertFalse(is_carmichael_number(239))
        self.assertFalse(is_carmichael_number(241))
        self.assertFalse(is_carmichael_number(251))
        self.assertFalse(is_carmichael_number(257))
        self.assertFalse(is_carmichael_number(263))
        self.assertFalse(is_carmichael_number(269))
        self.assertFalse(is_carmichael_number(271))
        self.assertFalse(is_carmichael_number(277))
        self.assertFalse(is_carmichael_number(281))
        self.assertFalse(is_carmichael_number(283))
        self.assertFalse(is_carmichael_number(293))
        self.assertFalse(is_carmichael_number(307))
        self.assertFalse(is_carmichael_number(311))
        self.assertFalse(is_carmichael_number(313))
        self.assertFalse(is_carmichael_number(317))
        self.assertFalse(is_carmichael_number(331))
        self.assertFalse(is_carmichael_number(337))
        self.assertFalse(is_carmichael_number(347))
        self.assertFalse(is_carmichael_number(349))
        self.assertFalse(is_carmichael_number(353))
        self.assertFalse(is_carmichael_number(359))
        self.assertFalse(is_carmichael_number(367))
        self.assertFalse(is_carmichael_number(373))
        self.assertFalse(is_carmichael_number(379))
        self.assertFalse(is_carmichael_number(383))
        self.assertFalse(is_carmichael_number(389))
        self.assertFalse(is_carmichael_number(397))
        self.assertFalse(is_carmichael_number(401))
        self.assertFalse(is_carmichael_number(409))
        self.assertFalse(is_carmichael_number(419))
        self.assertFalse(is_carmichael_number(421))
        self.assertFalse(is_carmichael_number(431))
        self.assertFalse(is_carmichael_number(433))
        self.assertFalse(is_carmichael_number(439))
        self.assertFalse(is_carmichael_number(443))
        self.assertFalse(is_carmichael_number(449))
        self.assertFalse(is_carmichael_number(457))
        self.assertFalse(is_carmichael_number(461))
        self.assertFalse(is_carmichael_number(463))
        self.assertFalse(is_carmichael_number(467))
        self.assertFalse(is_carmichael_number(479))
        self.assertFalse(is_carmichael_number(487))
        self.assertFalse(is_carmichael_number(491))
        self.assertFalse(is_carmichael_number(499))
        self.assertFalse(is_carmichael_number(503))
        self.assertFalse(is_carmichael_number(509))
        self.assertFalse(is_carmichael_number(521))
        self.assertFalse(is_carmichael_number(523))
        self.assertFalse(is_carmichael_number(541))
        self.assertFalse(is_carmichael_number(547))
        self.assertFalse(is_carmichael_number(557))
        self.assertFalse(is_carmichael_number(563))
        self.assertFalse(is_carmichael_number(569))
        self.assertFalse(is_carmichael_number(571))
        self.assertFalse(is_carmichael_number(577))
        self.assertFalse(is_carmichael_number(587))
        self.assertFalse(is_carmichael_number(593))
        self.assertFalse(is_carmichael_number(599))
        self.assertFalse(is_carmichael_number(601))
        self.assertFalse(is_carmichael_number(607))
        self.assertFalse(is_carmichael_number(613))
        self.assertFalse(is_carmichael_number(617))
        self.assertFalse(is_carmichael_number(619))
        self.assertFalse(is_carmichael_number(631))
        self.assertFalse(is_carmichael_number(641))
        self.assertFalse(is_carmichael_number(643))
        self.assertFalse(is_carmichael_number(647))
        self.assertFalse(is_carmichael_number(653))
        self.assertFalse(is_carmichael_number(659))
        self.assertFalse(is_carmichael_number(661))
        self.assertFalse(is_carmichael_number(673))
        self.assertFalse(is_carmichael_number(677))
        self.assertFalse(is_carmichael_number(683))
        self.assertFalse(is_carmichael_number(691))
        self.assertFalse(is_carmichael_number(701))
        self.assertFalse(is_carmichael_number(709))
        self.assertFalse(is_carmichael_number(719))
        self.assertFalse(is_carmichael_number(727))
        self.assertFalse(is_carmichael_number(733))
        self.assertFalse(is_carmichael_number(739))
        self.assertFalse(is_carmichael_number(743))
        self.assertFalse(is_carmichael_number(751))
        self.assertFalse(is_carmichael_number(757))
        self.assertFalse(is_carmichael_number(761))
        self.assertFalse(is_carmichael_number(769))
        self.assertFalse(is_carmichael_number(773))
        self.assertFalse(is_carmichael_number(787))
        self.assertFalse(is_carmichael_number(797))
        self.assertFalse(is_carmichael_number(809))
        self.assertFalse(is_carmichael_number(811))
        self.assertFalse(is_carmichael_number(821))
        self.assertFalse(is_carmichael_number(823))
        self.assertFalse(is_carmichael_number(827))
        self.assertFalse(is_carmichael_number(829))
        self.assertFalse(is_carmichael_number(839))
        self.assertFalse(is_carmichael_number(853))
        self.assertFalse(is_carmichael_number(857))
        self.assertFalse(is_carmichael_number(859))
        self.assertFalse(is_carmichael_number(863))
        self.assertFalse(is_carmichael_number(877))
        self.assertFalse(is_carmichael_number(881))
        self.assertFalse(is_carmichael_number(883))
        self.assertFalse(is_carmichael_number(887))
        self.assertFalse(is_carmichael_number(907))
        self.assertFalse(is_carmichael_number(911))
        self.assertFalse(is_carmichael_number(919))
        self.assertFalse(is_carmichael_number(929))
        self.assertFalse(is_carmichael_number(937))
        self.assertFalse(is_carmichael_number(941))
        self.assertFalse(is_carmichael_number(947))
        self.assertFalse(is_carmichael_number(953))
        self.assertFalse(is_carmichael_number(967))
        self.assertFalse(is_carmichael_number(971))
        self.assertFalse(is_carmichael_number(977))
        self.assertFalse(is_carmichael_number(983))
        self.assertFalse(is_carmichael_number(991))
        self.assertFalse(is_carmichael_number(997))

if __name__ == "__main__":
    unittest.main()