def test_exact_prime_factor_count():
    assert exact_prime_factor_count(51242183) == 3
    assert exact_prime_factor_count(2) == 1
    assert exact_prime_factor_count(3) == 1
    assert exact_prime_factor_count(4) == 1
    assert exact_prime_factor_count(5) == 1
    assert exact_prime_factor_count(6) == 2
    assert exact_prime_factor_count(7) == 1
    assert exact_prime_factor_count(8) == 1
    assert exact_prime_factor_count(9) == 1
    assert exact_prime_factor_count(10) == 2
    assert exact_prime_factor_count(11) == 1
    assert exact_prime_factor_count(12) == 2
    assert exact_prime_factor_count(13) == 1
    assert exact_prime_factor_count(14) == 2
    assert exact_prime_factor_count(15) == 2
    assert exact_prime_factor_count(16) == 1
    assert exact_prime_factor_count(17) == 1
    assert exact_prime_factor_count(18) == 2
    assert exact_prime_factor_count(19) == 1
    assert exact_prime_factor_count(20) == 2
    assert exact_prime_factor_count(21) == 2
    assert exact_prime_factor_count(22) == 2
    assert exact_prime_factor_count(23) == 1
    assert exact_prime_factor_count(24) == 2
    assert exact_prime_factor_count(25) == 1
    assert exact_prime_factor_count(26) == 2
    assert exact_prime_factor_count(27) == 1
    assert exact_prime_factor_count(28) == 2
    assert exact_prime_factor_count(29) == 1
    assert exact_prime_factor_count(30) == 3
    assert exact_prime_factor_count(31) == 1
    assert exact_prime_factor_count(32) == 1
    assert exact_prime_factor_count(33) == 2
    assert exact_prime_factor_count(34) == 2
    assert exact_prime_factor_count(35) == 2
    assert exact_prime_factor_count(36) == 2
    assert exact_prime_factor_count(37) == 1
    assert exact_prime_factor_count(38) == 2
    assert exact_prime_factor_count(39) == 2
    assert exact_prime_factor_count(40) == 2
    assert exact_prime_factor_count(41) == 1
    assert exact_prime_factor_count(42) == 3
    assert exact_prime_factor_count(43) == 1
    assert exact_prime_factor_count(44) == 2
    assert exact_prime_factor_count(45) == 2
    assert exact_prime_factor_count(46) == 2
    assert exact_prime_factor_count(47) == 1
    assert exact_prime_factor_count(48) == 2
    assert exact_prime_factor_count(49) == 1
    assert exact_prime_factor_count(50) == 2
    assert exact_prime_factor_count(51) == 2
    assert exact_prime_factor_count(52) == 2
    assert exact_prime_factor_count(53) == 1
    assert exact_prime_factor_count(54) == 3
    assert exact_prime_factor_count(55) == 2
    assert exact_prime_factor_count(56) == 2
    assert exact_prime_factor_count(57) == 2
    assert exact_prime_factor_count(58) == 2
    assert exact_prime_factor_count(59) == 1
    assert exact_prime_factor_count(60) == 3
    assert exact_prime_factor_count(61) == 1
    assert exact_prime_factor_count(62) == 2
    assert exact_prime_factor_count(63) == 2
    assert exact_prime_factor_count(64) == 1
    assert exact_prime_factor_count(65) == 2
    assert exact_prime_factor_count(66) == 3
    assert exact_prime_factor_count(67) == 1
    assert exact_prime_factor_count(68) == 2
    assert exact_prime_factor_count(69) == 2
    assert exact_prime_factor_count(70) == 3
    assert exact_prime_factor_count(71) == 1
    assert exact_prime_factor_count(72) == 3
    assert exact_prime_factor_count(73) == 1
    assert exact_prime_factor_count(74) == 2
    assert exact_prime_factor_count(75) == 2
    assert exact_prime_factor_count(76) == 2
    assert exact_prime_factor_count(77) == 2
    assert exact_prime_factor_count(78) == 3
    assert exact_prime_factor_count(79) == 1
    assert exact_prime_factor_count(80) == 2
    assert exact_prime_factor_count(81) == 1
    assert exact_prime_factor_count(82) == 2
    assert exact_prime_factor_count(83) == 1
    assert exact_prime_factor_count(84) == 3
    assert exact_prime_factor_count(85) == 2
    assert exact_prime_factor_count(86) == 2
    assert exact_prime_factor_count(87) == 2
    assert exact_prime_factor_count(88) == 2
    assert exact_prime_factor_count(89) == 1
    assert exact_prime_factor_count(90) == 3
    assert exact_prime_factor_count(91) == 2
    assert exact_prime_factor_count(92) == 2
    assert exact_prime_factor_count(93) == 2
    assert exact_prime_factor_count(94) == 2
    assert exact_prime_factor_count(95) == 2
    assert exact_prime_factor_count(96) == 3
    assert exact_prime_factor_count(97) == 1
    assert exact_prime_factor_count(98) == 3
    assert exact_prime_factor_count(99) == 2
    assert exact_prime_factor_count(100) == 2
    assert exact_prime_factor_count(101) == 1
    assert exact_prime_factor_count(102) == 3
    assert exact_prime_factor_count(103) == 1
    assert exact_prime_factor_count(104) == 2
    assert exact_prime_factor_count(105) == 3
    assert exact_prime_factor_count(106) == 2
    assert exact_prime_factor_count(107) == 1
    assert exact_prime_factor_count(108) == 3
    assert exact_prime_factor_count(109) == 1
    assert exact_prime_factor_count(110) == 3
    assert exact_prime_factor_count(111) == 2
    assert exact_prime_factor_count(112) == 2
    assert exact_prime_factor_count(113) == 1
    assert exact_prime_factor_count(114) == 2
    assert exact_prime_factor_count(115) == 2
    assert exact_prime_factor_count(116) == 2
    assert exact_prime_factor_count(117) == 2
    assert exact_prime_factor_count(118) == 2
    assert exact_prime_factor_count(119) == 2
    assert exact_prime_factor_count(120) == 4
    assert exact_prime_factor_count(121) == 1
    assert exact_prime_factor_count(122) == 2
    assert exact_prime_factor_count(123) == 2
    assert exact_prime_factor_count(124) == 2
    assert exact_prime_factor_count(125) == 1
    assert exact_prime_factor_count(126) == 3
    assert exact_prime_factor_count(127) == 1
    assert exact_prime_factor_count(128) == 1
    assert exact_prime_factor_count(129) == 2
    assert exact_prime_factor_count(130) == 3
    assert exact_prime_factor_count(131) == 1
    assert exact_prime_factor_count(132) == 3
    assert exact_prime_factor_count(133) == 2
    assert exact_prime_factor_count(134) == 2
    assert exact_prime_factor_count(135) == 2
    assert exact_prime_factor_count(136) == 2
    assert exact_prime_factor_count(137) == 1
    assert exact_prime_factor_count(138) == 3
    assert exact_prime_factor_count(139) == 1
    assert exact_prime_factor_count(140) == 3
    assert exact_prime_factor_count(141) == 2
    assert exact_prime_factor_count(142) == 2
    assert exact_prime_factor_count(143) == 2
    assert exact_prime_factor_count(144) == 4
    assert exact_prime_factor_count(145) == 2
    assert exact_prime_factor_count(146) == 2
    assert exact_prime_factor_count(147) == 2
    assert exact_prime_factor_count(148) == 2
    assert exact_prime_factor_count(149) == 1
    assert exact_prime_factor_count(150) == 3
    assert exact_prime_factor_count(151) == 1
    assert exact_prime_factor_count(152) == 2
    assert exact_prime_factor_count(153) == 2
    assert exact_prime_factor_count(154) == 3
    assert exact_prime_factor_count(155) == 2
    assert exact_prime_factor_count(156) == 3
    assert exact_prime_factor_count(157) == 1
    assert exact_prime_factor_count(158) == 2
    assert exact_prime_factor_count(159) == 2
    assert exact_prime_factor_count(160) == 3
    assert exact_prime_factor_count(161) == 2
    assert exact_prime_factor_count(162) == 3
    assert exact_prime_factor_count(163) == 1
    assert exact_prime_factor_count(164) == 2
    assert exact_prime_factor_count(165) == 3
    assert exact_prime_factor_count(166) == 2
    assert exact_prime_factor_count(167) == 1
    assert exact_prime_factor_count(168) == 4
    assert exact_prime_factor_count(169) == 1
    assert exact_prime_factor_count(170) == 2
    assert exact_prime_factor_count(171) == 2
    assert exact_prime_factor_count(172) == 2
    assert exact_prime_factor_count(173) == 1
    assert exact_prime_factor_count(174) == 3
    assert exact_prime_factor_count(175) == 2
    assert exact_prime_factor_count(176) == 2
    assert exact_prime_factor_count(177) == 2
    assert exact_prime_factor_count(178) == 2
    assert exact_prime_factor_count(179) == 1
    assert exact_prime_factor_count(180) == 4
    assert exact_prime_factor_count(181) == 1
    assert exact_prime_factor_count(182) == 3
    assert exact_prime_factor_count(183) == 2
    assert exact_prime_factor_count(184) == 2
    assert exact_prime_factor_count(185) == 2
    assert exact_prime_factor_count(186) == 3
    assert exact_prime_factor_count(187) == 2
    assert exact_prime_factor_count(188) == 2
    assert exact_prime_factor_count(189) == 3
    assert exact_prime_factor_count(190) == 3
    assert exact_prime_factor_count(191) == 1
    assert exact_prime_factor_count(192) == 4
    assert exact_prime_factor_count(193) == 1
    assert exact_prime_factor_count(194) == 2
    assert exact_prime_factor_count(195) == 3
    assert exact_prime_factor_count(196) == 2
    assert exact_prime_factor_count(197) == 1
    assert exact_prime_factor_count(198) == 3
    assert exact_prime_factor_count(199) == 1
    assert exact_prime_factor_count(200) == 3
    assert exact_prime_factor_count(201) == 2
    assert exact_prime_factor_count(202) == 2
    assert exact_prime_factor_count(203) == 2
    assert exact_prime_factor_count(204) == 3
    assert exact_prime_factor_count(205) == 2
    assert exact_prime_factor_count(206) == 2
    assert exact_prime_factor_count(207) == 2
    assert exact_prime_factor_count(208) == 2
    assert exact_prime_factor_count(209) == 2
    assert exact_prime_factor_count(210) == 4
    assert exact_prime_factor_count(211) == 1
    assert exact_prime_factor_count(212) == 2
    assert exact_prime_factor_count(213) == 2
    assert exact_prime_factor_count(214) == 2
    assert exact_prime_factor_count(215) == 2
    assert exact_prime_factor_count(216) == 4
    assert exact_prime_factor_count(217) == 2
    assert exact_prime_factor_count(218) == 2
    assert exact_prime_factor_count(219) == 2
    assert exact_prime_factor_count(220) == 3
    assert exact_prime_factor_count(221) == 2
    assert exact_prime_factor_count(222) == 3
    assert exact_prime_factor_count(223) == 1
    assert exact_prime_factor_count(224) == 3
    assert exact_prime_factor_count(225) == 2
    assert exact_prime_factor_count(226) == 2
    assert exact_prime_factor_count(227) == 1
    assert exact_prime_factor_count(228) == 2
    assert exact_prime_factor_count(229) == 1
    assert exact_prime_factor_count(230) == 3
    assert exact_prime_factor_count(231) == 2
    assert exact_prime_factor_count(232) == 2
    assert exact_prime_factor_count(233) == 1
    assert exact_prime_factor_count(234) == 3
    assert exact_prime_factor_count(235) == 2
    assert exact_prime_factor_count(236) == 2
    assert exact_prime_factor_count(237) == 2
    assert exact_prime_factor_count(238) == 2
    assert exact_prime_factor_count(239) == 1
    assert exact_prime_factor_count(240) == 4
    assert exact_prime_factor_count(241) == 1
    assert exact_prime_factor_count(242) == 2
    assert exact_prime_factor_count(243) == 2
    assert exact_prime_factor_count(244) == 2
    assert exact_prime_factor_count(245) == 2
    assert exact_prime_factor_count(246) == 3
    assert exact_prime_factor_count(247) == 2
    assert exact_prime_factor_count(248) == 2
    assert exact_prime_factor_count(249) == 2
    assert exact_prime_factor_count(250) == 3
    assert exact_prime_factor_count(251) == 1
    assert exact_prime_factor_count(252) == 4
    assert exact_prime_factor_count(253) == 2
    assert exact_prime_factor_count(254) == 2
    assert exact_prime_factor_count(255) == 2
    assert exact_prime_factor_count(256) == 1
    assert exact_prime_factor_count(257) == 1
    assert exact_prime_factor_count(258) == 3
    assert exact_prime_factor_count(259) == 2
    assert exact_prime_factor_count(260) == 3
    assert exact_prime_factor_count(261) == 2
    assert exact_prime_factor_count(262) == 2
    assert exact_prime_factor_count(263) == 1
    assert exact_prime_factor_count(264) == 3
    assert exact_prime_factor_count(265) == 2
    assert exact_prime_factor_count(266) == 2
    assert exact_prime_factor_count(267) == 2
    assert exact_prime_factor_count(268) == 2
    assert exact_prime_factor_count(269) == 1
    assert exact_prime_factor_count(270) == 4
    assert exact_prime_factor_count(271) == 1
    assert exact_prime_factor_count(272) == 2
    assert exact_prime_factor_count(273) == 2
    assert exact_prime_factor_count(274) == 2
    assert exact_prime_factor_count(275) == 2
    assert exact_prime_factor_count(276) == 3
    assert exact_prime_factor_count(277) == 1
    assert exact_prime_factor_count(278) == 2
    assert exact_prime_factor_count(279) == 2
    assert exact_prime_factor_count(280) == 3
    assert exact_prime_factor_count(281) == 1
    assert exact_prime_factor_count(282) == 3
    assert exact_prime_factor_count(283) == 1
    assert exact_prime_factor_count(284) == 2
    assert exact_prime_factor_count(285) == 2
    assert exact_prime_factor_count(286) == 2
    assert exact_prime_factor_count(287) == 2
    assert exact_prime_factor_count(288) == 4
    assert exact_prime_factor_count(289) == 1
    assert exact_prime_factor_count(290) == 2
    assert exact_prime_factor_count(291) == 2
    assert exact_prime_factor_count(292) == 2
    assert exact_prime_factor_count(293) == 1
    assert exact_prime_factor_count(294) == 3
    assert exact_prime_factor_count(295) == 2
    assert exact_prime_factor_count(296) == 2
    assert exact_prime_factor_count(297) == 2
    assert exact_prime_factor_count(298) == 2
    assert exact_prime_factor_count(299) == 2
    assert exact_prime_factor_count(300) == 4
    assert exact_prime_factor_count(301) == 2
    assert exact_prime_factor_count(302) == 2
    assert exact_prime_factor_count(303) == 2
    assert exact_prime_factor_count(304) == 2
    assert exact_prime_factor_count(305) == 2
    assert exact_prime_factor_count(306) == 3
    assert exact_prime_factor_count(307) == 1
    assert exact_prime_factor_count(308) == 3
    assert exact_prime_factor_count(309) == 2
    assert exact_prime_factor_count(310) == 3
    assert exact_prime_factor_count(311) == 1
    assert exact_prime_factor_count(312) == 3
    assert exact_prime_factor_count(313) == 1
    assert exact_prime_factor_count(314) == 2
    assert exact_prime_factor_count(315) == 3
    assert exact_prime_factor_count(316) == 2
    assert exact_prime_factor_count(317) == 1
    assert exact_prime_factor_count(318) == 3
    assert exact_prime_factor_count(319) == 2
    assert exact_prime_factor_count(320) == 3
    assert exact_prime_factor_count(321) == 2
    assert exact_prime_factor_count(322) == 2
    assert exact_prime_factor_count(323) == 2
    assert exact_prime_factor_count(324) == 4
    assert exact_prime_factor_count(325) == 2
    assert exact_prime_factor_count(326) == 2
    assert exact_prime_factor_count(327) == 2
    assert exact_prime_factor_count(328) == 2
    assert exact_prime_factor_count(329) == 2
    assert exact_prime_factor_count(330) == 4
    assert exact_prime_factor_count(331) == 1
    assert exact_prime_factor_count(332) == 2
    assert exact_prime_factor_count(333) == 2
    assert exact_prime_factor_count(334) == 2
    assert exact_prime_factor_count(335) == 2
    assert exact_prime_factor_count(336) == 4
    assert exact_prime_factor_count(337) == 1
    assert exact_prime_factor_count(338) == 2
    assert exact_prime_factor_count(339) == 2
    assert exact_prime_factor_count(340) == 3
    assert exact_prime_factor_count(341) == 2
    assert exact_prime_factor_count(342) == 3
    assert exact_prime_factor_count(343) == 2
    assert exact_prime_factor_count(344) == 2
    assert exact_prime_factor_count(345) == 2
    assert exact_prime_factor_count(346) == 2
    assert exact_prime_factor_count(347) == 1
    assert exact_prime_factor_count(348) == 3
    assert exact_prime_factor_count(349) == 1
    assert exact_prime_factor_count(350) == 3
    assert exact_prime_factor_count(351) == 2
    assert exact_prime_factor_count(352) == 2
    assert exact_prime_factor_count(353) == 1
    assert exact_prime_factor_count(354) == 3
    assert exact_prime_factor_count(355) == 2
    assert exact_prime_factor_count(356) == 2
    assert exact_prime_factor_count(357) == 2
    assert exact_prime_factor_count(358) == 2
    assert exact_prime_factor_count(359) == 1
    assert exact_prime_factor_count(360) == 4
    assert exact_prime_factor_count(361) == 1
    assert exact_prime_factor_count(362) == 2
    assert exact_prime_factor_count(363) == 2
    assert exact_prime_factor_count(364) == 2
    assert exact_prime_factor_count(365) == 2
    assert exact_prime_factor_count(366) == 3
    assert exact_prime_factor_count(367) == 1
    assert exact_prime_factor_count(368) == 2
    assert exact_prime_factor_count(369) == 2
    assert exact_prime_factor_count(370) == 3
    assert exact_prime_factor_count(371) == 2
    assert exact_prime_factor_count(372) == 3
    assert exact_prime_factor_count(373) == 1
    assert exact_prime_factor_count(374) == 2
    assert exact_prime_factor_count(375) == 3
    assert exact_prime_factor_count(376) == 2
    assert exact_prime_factor_count(377) == 2
    assert exact_prime_factor_count(378) == 3
    assert exact_prime_factor_count(379) == 1
    assert exact_prime_factor_count(380) == 3
    assert exact_prime_factor_count(381) == 2
    assert exact_prime_factor_count(382) == 2
    assert exact_prime_factor_count(383) == 1
    assert exact_prime_factor_count(384) == 4
    assert exact_prime_factor_count(385) == 2
    assert exact_prime_factor_count(386) == 2
    assert exact_prime_factor_count(387) == 2
    assert exact_prime_factor_count(388) == 2
    assert exact_prime_factor_count(389) == 1
    assert exact_prime_factor_count(390) == 4
    assert exact_prime_factor_count(391) == 2
    assert exact_prime_factor_count(392) == 3
    assert exact_prime_factor_count(393) == 2
    assert exact_prime_factor_count(394) == 2
    assert exact_prime_factor_count(395) == 2
    assert exact_prime_factor_count(396) == 4
    assert exact_prime_factor_count(397) == 1
    assert exact_prime_factor_count(398) == 2
    assert exact_prime_factor_count(399) == 3
    assert exact_prime_factor_count(400) == 3
    assert exact_prime_factor_count(401) == 1
    assert exact_prime_factor_count(402) == 3
    assert exact_prime_factor_count(403) == 2
    assert exact_prime_factor_count(404) == 2
    assert exact_prime_factor_count(405) == 2
    assert exact_prime_factor_count(406) == 2
    assert exact_prime_factor_count(407) == 2
    assert exact_prime_factor_count(408) == 3
    assert exact_prime_factor_count(409) == 1
    assert exact_prime_factor_count(410) == 3
    assert exact_prime_factor_count(411) == 2
    assert exact_prime_factor_count(412) == 2
    assert exact_prime_factor_count(413) == 2
    assert exact_prime_factor_count(414) == 3
    assert exact_prime_factor_count(415) == 2
    assert exact_prime_factor_count(416) == 2
    assert exact_prime_factor_count(417) == 2
    assert exact_prime_factor_count(418) == 2
    assert exact_prime_factor_count(419) == 1
    assert exact_prime_factor_count(420) == 4
    assert exact_prime_factor_count(421) == 1
    assert exact_prime_factor_count(422) == 2
    assert exact_prime_factor_count(423) == 2
    assert exact_prime_factor_count(424) == 2
    assert exact_prime_factor_count(425) == 2
    assert exact_prime_factor_count(426) == 3
    assert exact_prime_factor_count(427) == 2
    assert exact_prime_factor_count(428) == 2
    assert exact_prime_factor_count(429) == 2
    assert exact_prime_factor_count(430) == 3
    assert exact_prime_factor_count(431) == 1
    assert exact_prime_factor_count(432) == 4
    assert exact_prime_factor_count(433) == 1
    assert exact_prime_factor_count(434) == 2
    assert exact_prime_factor_count(435) == 2
    assert exact_prime_factor_count(436) == 2
    assert exact_prime_factor_count(437) == 2
    assert exact_prime_factor_count(438) == 3
    assert exact_prime_factor_count(439) == 1
    assert exact_prime_factor_count(440) == 3
    assert exact_prime_factor_count(441) == 2
    assert exact_prime_factor_count(442) == 2
    assert exact_prime_factor_count(443) == 1
    assert exact_prime_factor_count(444) == 3
    assert exact_prime_factor_count(445) == 2
    assert exact_prime_factor_count(446) == 2
    assert exact_prime_factor_count(447) == 2
    assert exact_prime_factor_count(448) == 3
    assert exact_prime_factor_count(449) == 1
    assert exact_prime_factor_count(450) == 4
    assert exact_prime_factor_count(451) == 2
    assert exact_prime_factor_count(452) == 2
    assert exact_prime_factor_count(453) == 2
    assert exact_prime_factor_count(454) == 2
    assert exact_prime_factor_count(455) == 2
    assert exact_prime_factor_count(456) == 3
    assert exact_prime_factor_count(457) == 1
    assert exact_prime_factor_count(458) == 2
    assert exact_prime_factor_count(459) == 2
    assert exact_prime_factor_count(460) == 3
    assert exact_prime_factor_count(461) == 1
    assert exact_prime_factor_count(462) == 3
    assert exact_prime_factor_count(463) == 1
    assert exact_prime_factor_count(464) == 2
    assert exact_prime_factor_count(465) == 3
    assert exact_prime_factor_count(466) == 2
    assert exact_prime_factor_count(467) == 1
    assert exact_prime_factor_count(468) == 3
    assert exact_prime_factor_count(469) == 2
    assert exact_prime_factor_count(470) == 2
    assert exact_prime_factor_count(471) == 2
    assert exact_prime_factor_count(472) == 2
    assert exact_prime_factor_count(473) == 2
    assert exact_prime_factor_count(474) == 2
    assert exact_prime_factor_count(475) == 2
    assert exact_prime_factor_count(476) == 2
    assert exact_prime_factor_count(477) == 2
    assert exact_prime_factor_count(478) == 2
    assert exact_prime_factor_count(479) == 1
    assert exact_prime_factor_count(480) == 5
    assert exact_prime_factor_count(481) == 2
    assert exact_prime_factor_count(482) == 2
    assert exact_prime_factor_count(483) == 2
    assert exact_prime_factor_count(484) == 2
    assert exact_prime_factor_count(485) == 2
    assert exact_prime_factor_count(486) == 4
    assert exact_prime_factor_count(487) == 1
    assert exact_prime_factor_count(488) == 2
    assert exact_prime_factor_count(489) == 2
    assert exact_prime_factor_count(490) == 3
    assert exact_prime_factor_count(491) == 1
    assert exact_prime_factor_count(492) == 3
    assert exact_prime_factor_count(493) == 2
    assert exact_prime_factor_count(494) == 2
    assert exact_prime_factor_count(495) == 3
    assert exact_prime_factor_count(496) == 3
    assert exact_prime_factor_count(497) == 2
    assert exact_prime_factor_count(498) == 3
    assert exact_prime_factor_count(499) == 1
    assert exact_prime_factor_count(500) == 3
    assert exact_prime_factor_count(501) == 2
    assert exact_prime_factor_count(502) == 2
    assert exact_prime_factor_count(503) == 1
    assert exact_prime_factor_count(504) == 5
    assert exact_prime_factor_count(505) == 2
    assert exact_prime_factor_count(506) == 2
    assert exact_prime_factor_count(507) == 2
    assert exact_prime_factor_count(508) == 2
    assert exact_prime_factor_count(509) == 1
    assert exact_prime_factor_count(510) == 4
    assert exact_prime_factor_count(511) == 2
    assert exact_prime_factor_count(512) == 1
    assert exact_prime_factor_count(513) == 2
    assert exact_prime_factor_count(514) == 2
    assert exact_prime_factor_count(515) == 2
    assert exact_prime_factor_count(516) == 3
    assert exact_prime_factor_count(517) == 2
    assert exact_prime_factor_count(518) == 2
    assert exact_prime_factor_count(519) == 2
    assert exact_prime_factor_count(520) == 3
    assert exact_prime_factor_count(521) == 1
    assert exact_prime_factor_count(522) == 3
    assert exact_prime_factor_count(523) == 1
    assert exact_prime_factor_count(524) == 2
    assert exact_prime_factor_count(525) == 3
    assert exact_prime_factor_count(526) == 2
    assert exact_prime_factor_count(527) == 2
    assert exact_prime_factor_count(528) == 4
    assert exact_prime_factor_count(529) == 1
    assert exact_prime_factor_count(530) == 2
    assert exact_prime_factor_count(531) == 2
    assert exact_prime_factor_count(532) == 2
    assert exact_prime_factor_count(533) == 2
    assert exact_prime_factor_count(534) == 3
    assert exact_prime_factor_count(535) == 2
    assert exact_prime_factor_count(536) == 2
    assert exact_prime_factor_count(537) == 2
    assert exact_prime_factor_count(538) == 2
    assert exact_prime_factor_count(539) == 2
    assert exact_prime_factor_count(540) == 4
    assert exact_prime_factor_count(541) == 1
    assert exact_prime_factor_count(542) == 2
    assert exact_prime_factor_count(543) == 2
    assert exact_prime_factor_count(544) == 2
    assert exact_prime_factor_count(545) == 2
    assert exact_prime_factor_count(546) == 3
    assert exact_prime_factor_count(547) == 1
    assert exact_prime_factor_count(548) == 2
    assert exact_prime_factor_count(549) == 2
    assert exact_prime_factor_count(550) == 3
    assert exact_prime_factor_count(551) == 2
    assert exact_prime_factor_count(552) == 3
    assert exact_prime_factor_count(553) == 2
    assert exact_prime_factor_count(554) == 2
    assert exact_prime_factor_count(555) == 2
    assert exact_prime_factor_count(556) == 2
    assert exact_prime_factor_count(557) == 1
    assert exact_prime_factor_count(558) == 3
    assert exact_prime_factor_count(559) == 2
    assert exact_prime_factor_count(560) == 4
    assert exact_prime_factor_count(561) == 2
    assert exact_prime_factor_count(562) == 2
    assert exact_prime_factor_count(563) == 1
    assert exact_prime_factor_count(564) == 3
    assert exact_prime_factor_count(565) == 2
    assert exact_prime_factor_count(566) == 2
    assert exact_prime_factor_count(567) == 3
    assert exact_prime_factor_count(568) == 2
    assert exact_prime_factor_count(569) == 1
    assert exact_prime_factor_count(570) == 4
    assert exact_prime_factor_count(571) == 1
    assert exact_prime_factor_count(572) == 2
    assert exact_prime_factor_count(573) == 2
    assert exact_prime_factor_count(574) == 2
    assert exact_prime_factor_count(575) == 2
    assert exact_prime_factor_count(576) == 5
    assert exact_prime_factor_count(577) == 1
    assert exact_prime_factor_count(578) == 2
    assert exact_prime_factor_count(579) == 2
    assert exact_prime_factor_count(580) == 3
    assert exact_prime_factor_count(581) == 2
    assert exact_prime_factor_count(582) == 3
    assert exact_prime_factor_count(583) == 2
    assert exact_prime_factor_count(584) == 2
    assert exact_prime_factor_count(585) == 3
    assert exact_prime_factor_count(586) == 2
    assert exact_prime_factor_count(587) == 1
    assert exact_prime_factor_count(588) == 4
    assert exact_prime_factor_count(589) == 2
    assert exact_prime_factor_count(590) == 2
    assert exact_prime_factor_count(591) == 2
    assert exact_prime_factor_count(592) == 2
    assert exact_prime_factor_count(593) == 1
    assert exact_prime_factor_count(594) == 4
    assert exact_prime_factor_count(595) == 2
    assert exact_prime_factor_count(596) == 2
    assert exact_prime_factor_count(597) == 2
    assert exact_prime_factor_count(598) == 2
    assert exact_prime_factor_count(599) == 1
    assert exact_prime_factor_count(600) == 5
    assert exact_prime_factor_count(601) == 1
    assert exact_prime_factor_count(602) == 2
    assert exact_prime_factor_count(603) == 2
    assert exact_prime_factor_count(604) == 2
    assert exact_prime_factor_count(605) == 2
    assert exact_prime_factor_count(606) == 3
    assert exact_prime_factor_count(607) == 1
    assert exact_prime_factor_count(608) == 2
    assert exact_prime_factor_count(609) == 2
    assert exact_prime_factor_count(610) == 3
    assert exact_prime_factor_count(611) == 2
    assert exact_prime_factor_count(612) == 4
    assert exact_prime_factor_count(613) == 1
    assert exact_prime_factor_count(614) == 2
    assert exact_prime_factor_count(615) == 2
    assert exact_prime_factor_count(616) == 3
    assert exact_prime_factor_count(617) == 1
    assert exact_prime_factor_count(618) == 3
    assert exact_prime_factor_count(619) == 1
    assert exact_prime_factor_count(620) == 3
    assert exact_prime_factor_count(621) == 2
    assert exact_prime_factor_count(622) == 2
    assert exact_prime_factor_count(623) == 2
    assert exact_prime_factor_count(624) == 4
    assert exact_prime_factor_count(625) == 2
    assert exact_prime_factor_count(626) == 2
    assert exact_prime_factor_count(627) == 2
    assert exact_prime_factor_count(628) == 2
    assert exact_prime_factor_count(629) == 2
    assert exact_prime_factor_count(630) == 4
    assert exact_prime_factor_count(631) == 1
    assert exact_prime_factor_count(632) == 2
    assert exact_prime_factor_count(633) == 2
    assert exact_prime_factor_count(634) == 2
    assert exact_prime_factor_count(635) == 2
    assert exact_prime_factor_count(636) == 3
    assert exact_prime_factor_count(637) == 2
    assert exact_prime_factor_count(638) == 2
    assert exact_prime_factor_count(639) == 2
    assert exact_prime_factor_count(640) == 4
    assert exact_prime_factor_count(641) == 1
    assert exact_prime_factor_count(642) == 3
    assert exact_prime_factor_count(643) == 1
    assert exact_prime_factor_count(644) == 2
    assert exact_prime_factor_count(645) == 2
    assert exact_prime_factor_count(646) == 2
    assert exact_prime_factor_count(647) == 1
    assert exact_prime_factor_count(648) == 5
    assert exact_prime_factor_count(649) == 2
    assert exact_prime_factor_count(650) == 3
    assert exact_prime_factor_count(651) == 2
    assert exact_prime_factor_count(652) == 2
    assert exact_prime_factor_count(653) == 1
    assert exact_prime_factor_count(654) == 3
    assert exact_prime_factor_count(655) == 2
    assert exact_prime_factor_count(656) == 2
    assert exact_prime_factor_count(657) == 2
    assert exact_prime_factor_count(658) == 2
    assert exact_prime_factor_count(659) == 1
    assert exact_prime_factor_count(660) == 4
    assert exact_prime_factor_count(661) == 1
    assert exact_prime_factor_count(662) == 2
    assert exact_prime_factor_count(663) == 2
    assert exact_prime_factor_count(664) == 2
    assert exact_prime_factor_count(665) == 2
    assert exact_prime_factor_count(666) == 3
    assert exact_prime_factor_count(667) == 2
    assert exact_prime_factor_count(668) == 2
    assert exact_prime_factor_count(669) == 2
    assert exact_prime_factor_count(670) == 3
    assert exact_prime_factor_count(671) == 2
    assert exact_prime_factor_count(672) == 4
    assert exact_prime_factor_count(673) == 1
    assert exact_prime_factor_count(674) == 2
    assert exact_prime_factor_count(675) == 3
    assert exact_prime_factor_count(676) == 2
    assert exact_prime_factor_count(677) == 1
    assert exact_prime_factor_count(678) == 3
    assert exact_prime_factor_count(679) == 2
    assert exact_prime_factor_count(680) == 3
    assert exact_prime_factor_count(681) == 2
    assert exact_prime_factor_count(682) == 2
    assert exact_prime_factor_count(683) == 1
    assert exact_prime_factor_count(684) == 4
    assert exact_prime_factor_count(685) == 2
    assert exact_prime_factor_count(686) == 2
    assert exact_prime_factor_count(687) == 2
    assert exact_prime_factor_count(688) == 2
    assert exact_prime_factor_count(689) == 2
    assert exact_prime_factor_count(690) == 4
    assert exact_prime_factor_count(691) == 1
    assert exact_prime_factor_count(692) == 2
    assert exact_prime_factor_count(693) == 3
    assert exact_prime_factor_count(694) == 2
    assert exact_prime_factor_count(695) == 2
    assert exact_prime_factor_count(696) == 3
    assert exact_prime_factor_count(697) == 2
    assert exact_prime_factor_count(698) == 2
    assert exact_prime_factor_count(699) == 2
    assert exact_prime_factor_count(700) == 3
    assert exact_prime_factor_count(701) == 1
    assert exact_prime_factor_count(702) == 4
    assert exact_prime_factor_count(703) == 2
    assert exact_prime_factor_count(704) == 2
    assert exact_prime_factor_count(705) == 2
    assert exact_prime_factor_count(706) == 2
    assert exact_prime_factor_count(707) == 2
    assert exact_prime_factor_count(708) == 3
    assert exact_prime_factor_count(709) == 1
    assert exact_prime_factor_count(710) == 3
    assert exact_prime_factor_count(711) == 2
    assert exact_prime_factor_count(712) == 2
    assert exact_prime_factor_count(713) == 2
    assert exact_prime_factor_count(714) == 3
    assert exact_prime_factor_count(715) == 2
    assert exact_prime_factor_count(716) == 2
    assert exact_prime_factor_count(717) == 2
    assert exact_prime_factor_count(718) == 2
    assert exact_prime_factor_count(719) == 1
    assert exact_prime_factor_count(720) == 6
    assert exact_prime_factor_count(721) == 2
    assert exact_prime_factor_count(722) == 2
    assert exact_prime_factor_count(723) == 2
    assert exact_prime_factor_count(724) == 2
    assert exact_prime_factor_count(725) == 2
    assert exact_prime_factor_count(726) == 3
    assert exact_prime_factor_count(727) == 1
    assert exact_prime_factor_count(728) == 3
    assert exact_prime_factor_count(729) == 2
    assert exact_prime_factor_count(730) == 3
    assert exact_prime_factor_count(731) == 2
    assert exact_prime_factor_count(732) == 3
    assert exact_prime_factor_count(733) == 1
    assert exact_prime_factor_count(734) == 2
    assert exact_prime_factor_count(735) == 3
    assert exact_prime_factor_count(736) == 2
    assert exact_prime_factor_count(737) == 2
    assert exact_prime_factor_count(738) == 3
    assert exact_prime_factor_count(739) == 1
    assert exact_prime_factor_count(740) == 3
    assert exact_prime_factor_count(741) == 2
    assert exact_prime_factor_count(742) == 2
    assert exact_prime_factor_count(743) == 1
    assert exact_prime_factor_count(744) == 4
    assert exact_prime_factor_count(745) == 2
    assert exact_prime_factor_count(746) == 2
    assert exact_prime_factor_count(747) == 2
    assert exact_prime_factor_count(748) == 2
    assert exact_prime_factor_count(749) == 2
    assert exact_prime_factor_count(750) == 4
    assert exact_prime_factor_count(751) == 1
    assert exact_prime_factor_count(752) == 2
    assert exact_prime_factor_count(753) == 2
    assert exact_prime_factor_count(754) == 2
    assert exact_prime_factor_count(755) == 2
    assert exact_prime_factor_count(756) == 4
    assert exact_prime_factor_count(757) == 1
    assert exact_prime_factor_count(758) == 2
    assert exact_prime_factor_count(759) == 2
    assert exact_prime_factor_count(760) == 3
    assert exact_prime_factor_count(761) == 1
    assert exact_prime_factor_count(762) == 3
    assert exact_prime_factor_count(763) == 2
    assert exact_prime_factor_count(764) == 2
    assert exact_prime_factor_count(765) == 3
    assert exact_prime_factor_count(766) == 2
    assert exact_prime_factor_count(767) == 2
    assert exact_prime_factor_count(768) == 5
    assert exact_prime_factor_count(769) == 1
    assert exact_prime_factor_count(770) == 3
    assert exact_prime_factor_count(771) == 2
    assert exact_prime_factor_count(772) == 2
    assert exact_prime_factor_count(773) == 1
    assert exact_prime_factor_count(774) == 3
    assert exact_prime_factor_count(775) == 2
    assert exact_prime_factor_count(776) == 2
    assert exact_prime_factor_count(777) == 2
    assert exact_prime_factor_count(778) == 2
    assert exact_prime_factor_count(779) == 2
    assert exact_prime_factor_count(780) == 4
    assert exact_prime_factor_count(781) == 2
    assert exact_prime_factor_count(782) == 2
    assert exact_prime_factor_count(783) == 2
    assert exact_prime_factor_count(784) == 3
    assert exact_prime_factor_count(785) == 2
    assert exact_prime_factor_count(786) == 2
    assert exact_prime_factor_count(787) == 1
    assert exact_prime_factor_count(788) == 2
    assert exact_prime_factor_count(789) == 2
    assert exact_prime_factor_count(790) == 3
    assert exact_prime_factor_count(791) == 2
    assert exact_prime_factor_count(792) == 4
    assert exact_prime_factor_count(793) == 2
    assert exact_prime_factor_count(794) == 2
    assert exact_prime_factor_count(795) == 2
    assert exact_prime_factor_count(796) == 2
    assert exact_prime_factor_count(797) == 1
    assert exact_prime_factor_count(798) == 4
    assert exact_prime_factor_count(799) == 2
    assert exact_prime_factor_count(800) == 3
    assert exact_prime_factor_count(801) == 2
    assert exact_prime_factor_count(802) == 2
    assert exact_prime_factor_count(803) == 2
    assert exact_prime_factor_count(804) == 3
    assert exact_prime_factor_count(805) == 2
    assert exact_prime_factor_count(806) == 2
    assert exact_prime_factor_count(807) == 2
    assert exact_prime_factor_count(808) == 2
    assert exact_prime_factor_count(809) == 1
    assert exact_prime_factor_count(810) == 4
    assert exact_prime_factor_count(811) == 1
    assert exact_prime_factor_count(812) == 2
    assert exact_prime_factor_count(813) == 2
    assert exact_prime_factor_count(814) == 2
    assert exact_prime_factor_count(815) == 2
    assert exact_prime_factor_count(816) == 4
    assert exact_prime_factor_count(817) == 2
    assert exact_prime_factor_count(818) == 2
    assert exact_prime_factor_count(819) == 3
    assert exact_prime_factor_count(820) == 3
    assert exact_prime_factor_count(821) == 1
    assert exact_prime_factor_count(822) == 3
    assert exact_prime_factor_count(823) == 1
    assert exact_prime_factor_count(824) == 2
    assert exact_prime_factor_count(825) == 3
    assert exact_prime_factor_count(826) == 2
    assert exact_prime_factor_count(827) == 1
    assert exact_prime_factor_count(828) == 3
    assert exact_prime_factor_count(829) == 1
    assert exact_prime_factor_count(830) == 3
    assert exact_prime_factor_count(831) == 2
    assert exact_prime_factor_count(832) == 2
    assert exact_prime_factor_count(833) == 2
    assert exact_prime_factor_count(834) == 3
    assert exact_prime_factor_count(835) == 2
    assert exact_prime_factor_count(836) == 2
    assert exact_prime_factor_count(837) == 2
    assert exact_prime_factor_count(838) == 2
    assert exact_prime_factor_count(839) == 1
    assert exact_prime_factor_count(840) == 5
    assert exact_prime_factor_count(841) == 2
    assert exact_prime_factor_count(842) == 2
    assert exact_prime_factor_count(843) == 2
    assert exact_prime_factor_count(844) == 2
    assert exact_prime_factor_count(845) == 2
    assert exact_prime_factor_count(846) == 3
    assert exact_prime_factor_count(847) == 2
    assert exact_prime_factor_count(848) == 2
    assert exact_prime_factor_count(849) == 2
    assert exact_prime_factor_count(850) == 3
    assert exact_prime_factor_count(851) == 2
    assert exact_prime_factor_count(852) == 3
    assert exact_prime_factor_count(853) == 1
    assert exact_prime_factor_count(854) == 2
    assert exact_prime_factor_count(855) == 3
    assert exact_prime_factor_count(856) == 2
    assert exact_prime_factor_count(857) == 1
    assert exact_prime_factor_count(858) == 3
    assert exact_prime_factor_count(859) == 1
    assert exact_prime_factor_count(860) == 3
    assert exact_prime_factor_count(861) == 2
    assert exact_prime_factor_count(862) == 2
    assert exact_prime_factor_count(863) == 1
    assert exact_prime_factor_count(864) == 6
    assert exact_prime_factor_count(865) == 2
    assert exact_prime_factor_count(866) == 2
    assert exact_prime_factor_count(867) == 2
    assert exact_prime_factor_count(868) == 2
    assert exact_prime_factor_count(869) == 2
    assert exact_prime_factor_count(870) == 4
    assert exact_prime_factor_count(871) == 2
    assert exact_prime_factor_count(872) == 2
    assert exact_prime_factor_count(873) == 2
    assert exact_prime_factor_count(874) == 2
    assert exact_prime_factor_count(875) == 2
    assert exact_prime_factor_count(876) == 4
    assert exact_prime_factor_count(877) == 1
    assert exact_prime_factor_count(878) == 2
    assert exact_prime_factor_count(879) == 2
    assert exact_prime_factor_count(880) == 4
    assert exact_prime_factor_count(881) == 1
    assert exact_prime_factor_count(882) == 4
    assert exact_prime_factor_count(883) == 1
    assert exact_prime_factor_count(884) == 2
    assert exact_prime_factor_count(885) == 2
    assert exact_prime_factor_count(886) == 2
    assert exact_prime_factor_count(887) == 1
    assert exact_prime_factor_count(888) == 3
    assert exact_prime_factor_count(889) == 2
    assert exact_prime_factor_count(890) == 3
    assert exact_prime_factor_count(891) == 2
    assert exact_prime_factor_count(892) == 2
    assert exact_prime_factor_count(893) == 2
    assert exact_prime_factor_count(894) == 3
    assert exact_prime_factor_count(895) == 2
    assert exact_prime_factor_count(896) == 3
    assert exact_prime_factor_count(897) == 2
    assert exact_prime_factor_count(898) == 2
    assert exact_prime_factor_count(899) == 2
    assert exact_prime_factor_count(900) == 5
    assert exact_prime_factor_count(901) == 2
    assert exact_prime_factor_count(902) == 2
    assert exact_prime_factor_count(903) == 2
    assert exact_prime_factor_count(904) == 2
    assert exact_prime_factor_count(905) == 2
    assert exact_prime_factor_count(906) == 3
    assert exact_prime_factor_count(907) == 1
    assert exact_prime_factor_count(908) == 2
    assert exact_prime_factor_count(909) == 2
    assert exact_prime_factor_count(910) == 4
    assert exact_prime_factor_count(911) == 1
    assert exact_prime_factor_count(912) == 4
    assert exact_prime_factor_count(913) == 2
    assert exact_prime_factor_count(914) == 2
    assert exact_prime_factor_count(915) == 2
    assert exact_prime_factor_count(916) == 2
    assert exact_prime_factor_count(917) == 2
    assert exact_prime_factor_count(918) == 4
    assert exact_prime_factor_count(919) == 1
    assert exact_prime_factor_count(920) == 3
    assert exact_prime_factor_count(921) == 2
    assert exact_prime_factor_count(922) == 2
    assert exact_prime_factor_count(923) == 2
    assert exact_prime_factor_count(924) == 4
    assert exact_prime_factor_count(925) == 2
    assert exact_prime_factor_count(926) == 2
    assert exact_prime_factor_count(927) == 2
    assert exact_prime_factor_count(928) == 3
    assert exact_prime_factor_count(929) == 1
    assert exact_prime_factor_count(930) == 4
    assert exact_prime_factor_count(931) == 2
    assert exact_prime_factor_count(932) == 2
    assert exact_prime_factor_count(933) == 2
    assert exact_prime_factor_count(934) == 2
    assert exact_prime_factor_count(935) == 2
    assert exact_prime_factor_count(936) == 5
    assert exact_prime_factor_count(937) == 1
    assert exact_prime_factor_count(938) == 2
    assert exact_prime_factor_count(939) == 2
    assert exact_prime_factor_count(940) == 3
    assert exact_prime_factor_count(941) == 1
    assert exact_prime_factor_count(942) == 3
    assert exact_prime_factor_count(943) == 2
    assert exact_prime_factor_count(944) == 2
    assert exact_prime_factor_count(945) == 3
    assert exact_prime_factor_count(946) == 2
    assert exact_prime_factor_count(947) == 1
    assert exact_prime_factor_count(948) == 3
    assert exact_prime_factor_count(949) == 2
    assert exact_prime_factor_count(950) == 3
    assert exact_prime_factor_count(951) == 2
    assert exact_prime_factor_count(952) == 3
    assert exact_prime_factor_count(953) == 1
    assert exact_prime_factor_count(954) == 3
    assert exact_prime_factor_count(955) == 2
    assert exact_prime_factor_count(956) == 2
    assert exact_prime_factor_count(957) == 2
    assert exact_prime_factor_count(958) == 2
    assert exact_prime_factor_count(959) == 2
    assert exact_prime_factor_count(960) == 7
    assert exact_prime_factor_count(961) == 1
    assert exact_prime_factor_count(962) == 2
    assert exact_prime_factor_count(963) == 2
    assert exact_prime_factor_count(964) == 2
    assert exact_prime_factor_count(965) == 2
    assert exact_prime_factor_count(966) == 3
    assert exact_prime_factor_count(967) == 1
    assert exact_prime_factor_count(968) == 2
    assert exact_prime_factor_count(969) == 2
    assert exact_prime_factor_count(970) == 3
    assert exact_prime_factor_count(971) == 1
    assert exact_prime_factor_count(972) == 5
    assert exact_prime_factor_count(973) == 2
    assert exact_prime_factor_count(974) == 2
    assert exact_prime_factor_count(975) == 2
    assert exact_prime_factor_count(976) == 2
    assert exact_prime_factor_count(977) == 1
    assert exact_prime_factor_count(978) == 3
    assert exact_prime_factor_count(979) == 2
    assert exact_prime_factor_count(980) == 4
    assert exact_prime_factor_count(981) == 2
    assert exact_prime_factor_count(982) == 2
    assert exact_prime_factor_count(983) == 1
    assert exact_prime_factor_count(984) == 4
    assert exact_prime_factor_count(985) == 2
    assert exact_prime_factor_count(986) == 2
    assert exact_prime_factor_count(987) == 2
    assert exact_prime_factor_count(988) == 2
    assert exact_prime_factor_count(989) == 2
    assert exact_prime_factor_count(990) == 4
    assert exact_prime_factor_count(991) == 1
    assert exact_prime_factor_count(992) == 3
    assert exact_prime_factor_count(993) == 2
    assert exact_prime_factor_count(994) == 2
    assert exact_prime_factor_count(995) == 2
    assert exact_prime_factor_count(996) == 4
    assert exact_prime_factor_count(997) == 1
    assert exact_prime_factor_count(998) == 2
    assert exact_prime_factor_count(999) == 2
    assert exact_prime_factor_count(1000) == 4
    assert exact_prime_factor_count(1001) == 2
    assert exact_prime_factor_count(1002) == 3
    assert exact_prime_factor_count(1003) == 2
    assert exact_prime_factor_count(1004) == 2
    assert exact_prime_factor_count(1005) == 2
    assert exact_prime_factor_count(1006) == 2
    assert exact_prime_factor_count(1007) == 2
    assert exact_prime_factor_count(1008) == 6
    assert exact_prime_factor_count(1009) == 1
    assert exact_prime_factor_count(1010) == 3
    assert exact_prime_factor_count(1011) == 1
    assert exact_prime_factor_count(1012) == 2
    assert exact_prime_factor_count(1013) == 1
    assert exact_prime_factor_count(1014) == 3
    assert exact_prime_factor_count(1015) == 2
    assert exact_prime_factor_count(1016) == 2
    assert exact_prime_factor_count(1017) == 2
    assert exact_prime_factor_count(1018) == 2
    assert exact_prime_factor_count(1019) == 1
    assert exact_prime_factor_count(1020) == 4
    assert exact_prime_factor_count(1021) == 1
    assert exact_prime_factor_count(1022) == 2
    assert exact_prime_factor_count(1023) == 2
    assert exact_prime_factor_count(1024) == 1
    assert exact_prime_factor_count(1025) == 2
    assert exact_prime_factor_count(1026) == 4
    assert exact_prime_factor_count(1027) == 2
    assert exact_prime_factor_count(1028) == 2
    assert exact_prime_factor_count(1029) == 2
    assert exact_prime_factor_count(1030) == 3
    assert exact_prime_factor_count(1031) == 1
    assert exact_prime_factor_count(1032) == 4
    assert exact_prime_factor_count(1033) == 1
    assert exact_prime_factor_count(1034) == 2
    assert exact_prime_factor_count(1035) == 2
    assert exact_prime_factor_count(1036) == 2
    assert exact_prime_factor_count(1037) == 2
    assert exact_prime_factor_count(1038) == 3
    assert exact_prime_factor_count(1039) == 1
    assert exact_prime_factor_count(1040) == 4
    assert exact_prime_factor_count(1041) == 2
    assert exact_prime_factor_count(1042) == 2
    assert exact_prime_factor_count(1043) == 1
    assert exact_prime_factor_count(1044) == 3
    assert exact_prime_factor_count(1045) == 2
    assert exact_prime_factor_count(1046) == 2
    assert exact_prime_factor_count(1047) == 2
    assert exact_prime_factor_count(1048) == 3
    assert exact_prime_factor_count(1049) == 1
    assert exact_prime_factor_count(1050) == 4
    assert exact_prime_factor_count(1051) == 1
    assert exact_prime_factor_count(1052) == 2
    assert exact_prime_factor_count(1053) == 2
    assert exact_prime_factor_count(1054) == 2
    assert exact_prime_factor_count(1055) == 2
    assert exact_prime_factor_count(1056) == 5
    assert exact_prime_factor_count(1057) == 2
    assert exact_prime_factor_count(1058) == 2
    assert exact_prime_factor_count(1059) == 2
    assert exact_prime_factor_count(1060) == 3
    assert exact_prime_factor_count(1061) == 1
    assert exact_prime_factor_count(1062) == 3
    assert exact_prime_factor_count(1063) == 1
    assert exact_prime_factor_count(1064) == 2
    assert exact_prime_factor_count(1065) == 2
    assert exact_prime_factor_count(1066) == 2
    assert exact_prime_factor_count(1067) == 1
    assert exact_prime_factor_count(1068) == 3
    assert exact_prime_factor_count(1069) == 1
    assert exact_prime_factor_count(1070) == 3
    assert exact_prime_factor_count(1071) == 2
    assert exact_prime_factor_count(1072) == 3
    assert exact_prime_factor_count(1073) == 2
    assert exact_prime_factor_count(1074) == 2
    assert exact_prime_factor_count(1075) == 2
    assert exact_prime_factor_count(1076) == 2
    assert exact_prime_factor_count(1077) == 2
    assert exact_prime_factor_count(1078) == 2
    assert exact_prime_factor_count(1079) == 2
    assert exact_prime_factor_count(1080) == 5
    assert exact_prime_factor_count(1081) == 2
    assert exact_prime_factor_count(1082) == 2
    assert exact_prime_factor_count(1083) == 2
    assert exact_prime_factor_count(1084) == 2
    assert exact_prime_factor_count(1085) == 2
    assert exact_prime_factor_count(1086) == 3
    assert exact_prime_factor_count(1087) == 1
    assert exact_prime_factor_count(1088) == 2
    assert exact_prime_factor_count(1089) == 2
    assert exact_prime_factor_count(1090) == 3
    assert exact_prime_factor_count(1091) == 2
    assert exact_prime_factor_count(1092) == 3
    assert exact_prime_factor_count(1093) == 1
    assert exact_prime_factor_count(1094) == 2
    assert exact_prime_factor_count(1095) == 2
    assert exact_prime_factor_count(1096) == 2
    assert exact_prime_factor_count(1097) == 1
    assert exact_prime_factor_count(1098) == 4
    assert exact_prime_factor_count(1099) == 2
    assert exact_prime_factor_count(1100) == 3
    assert exact_prime_factor_count(1101) == 2
    assert exact_prime_factor_count(1102) == 2
    assert exact_prime_factor_count(1103) == 1
    assert exact_prime_factor_count(1104) == 4
    assert exact_prime_factor_count(1105) == 2
    assert exact_prime_factor_count(1106) == 2
    assert exact_prime_factor_count(1107) == 2
    assert exact_prime_factor_count(1108) == 2
    assert exact_prime_factor_count(1109) == 1
    assert exact_prime_factor_count(1110) == 4
    assert exact_prime_factor_count(1111) == 2
    assert exact_prime_factor_count(1112) == 2
    assert exact_prime_factor_count(1113) == 2
    assert exact_prime_factor_count(1114) == 2
    assert exact_prime_factor_count(1115) == 2
    assert exact_prime_factor_count(1116) == 4
    assert exact_prime_factor_count(1117) == 1
    assert exact_prime_factor_count(1118) == 2
    assert exact_prime_factor_count(1119) == 2
    assert exact_prime_factor_count(1120) == 4
    assert exact_prime_factor_count(1121) == 2
    assert exact_prime_factor_count(1122) == 2
    assert exact_prime_factor_count(1123) == 1
    assert exact_prime_factor_count(1124) == 2
    assert exact_prime_factor_count(1125) == 3
    assert exact_prime_factor_count(1126) == 2
    assert exact_prime_factor_count(1127) == 2
    assert exact_prime_factor_count(1128) == 3
    assert exact_prime_factor_count(1129) == 1
    assert exact_prime_factor_count(1130) == 3
    assert exact_prime_factor_count(1131) == 2
    assert exact_prime_factor_count(1132) == 2
    assert exact_prime_factor_count(1133) == 2
    assert exact_prime_factor_count(1134) == 4
    assert exact_prime_factor_count(1135) == 2
    assert exact_prime_factor_count(1136) == 2
    assert exact_prime_factor_count(1137) == 2
    assert exact_prime_factor_count(1138) == 2
    assert exact_prime_factor_count(1139) == 1
    assert exact_prime_factor_count(1140) == 4
    assert exact_prime_factor_count(1141) == 2
    assert exact_prime_factor_count(1142) == 2
    assert exact_prime_factor_count(1143) == 2
    assert exact_prime_factor_count(1144) == 2
    assert exact_prime_factor_count(1145) == 2
    assert exact_prime_factor_count(1146) == 3
    assert exact_prime_factor_count(1147) == 2
    assert exact_prime_factor_count(1148) == 2
    assert exact_prime_factor_count(1149) == 2
    assert exact_prime_factor_count(1150) == 3
    assert exact_prime_factor_count(1151) == 1
    assert exact_prime_factor_count(1152) == 5
    assert exact_prime_factor_count(1153) == 1
    assert exact_prime_factor_count(1154) == 2
    assert exact_prime_factor_count(1155) == 2
    assert exact_prime_factor_count(1156) == 2
    assert exact_prime_factor_count(1157) == 1
    assert exact_prime_factor_count(1158) == 3
    assert exact_prime_factor_count(1159) == 2
    assert exact_prime_factor_count(1160) == 3
    assert exact_prime_factor_count(1161) == 1
    assert exact_prime_factor_count(1162) == 2
    assert exact_prime_factor_count(1163) == 1
    assert exact_prime_factor_count(1164) == 3
    assert exact_prime_factor_count(1165) == 2
    assert exact_prime_factor_count(1166) == 2
    assert exact_prime_factor_count(1167) == 2
    assert exact_prime_factor_count(1168) == 3
    assert exact_prime_factor_count(1169) == 2
    assert exact_prime_factor_count(1170) == 4
    assert exact_prime_factor_count(1171) == 2
    assert exact_prime_factor_count(1172) == 2
    assert exact_prime_factor_count(1173) == 2
    assert exact_prime_factor_count(1174) == 2
    assert exact_prime_factor_count(1175) == 2
    assert exact_prime_factor_count(1176) == 4
    assert exact_prime_factor_count(1177) == 2
    assert exact_prime_factor_count(1178) == 2
    assert exact_prime_factor_count(1179) == 2
    assert exact_prime_factor_count(1180) == 3
    assert exact_prime_factor_count(1181) == 1
    assert exact_prime_factor_count(1182) == 3
    assert exact_prime_factor_count(1183) == 2
    assert exact_prime_factor_count(1184) == 2
    assert exact_prime_factor_count(1185) == 2
    assert exact_prime_factor_count(1186) == 2
    assert exact_prime_factor_count(1187) == 1
    assert exact_prime_factor_count(1188) == 4
    assert exact_prime_factor_count(1189) == 2
    assert exact_prime_factor_count(1190) == 3
    assert exact_prime_factor_count(1191) == 2
    assert exact_prime_factor_count(1192) == 2
    assert exact_prime_factor_count(1193) == 1
    assert exact_prime_factor_count(1194) == 3
    assert exact_prime_factor_count(1195) == 2
    assert exact_prime_factor_count(1196) == 2
    assert exact_prime_factor_count(1197) == 2
    assert exact_prime_factor_count(1198) == 2
    assert exact_prime_factor_count(1199) == 2
    assert exact_prime_factor_count(1200) == 6
    assert exact_prime_factor_count(1201) == 1
    assert exact_prime_factor_count(1202) == 2
    assert exact_prime_factor_count(1203) == 2
    assert exact_prime_factor_count(1204) == 2
    assert exact_prime_factor_count(1205)